obs_info:
    - spec: null
      beam_info: 30. # [1/3600, 1/3600] [deg]
      T_bg: 0.
      need_cmb: True
      noise: 1.

    # Use the following for multiple observed segments
    #- spec: None
    #  beam_info: 30. # [1/3600, 1/3600] [deg]
    #  T_bg: 0.
    #  need_cmb: True
fname_base: null
sl_model:
  fname_db: null
  trunc: 5.
  eps_grid: 1.e-3
  params:
    theta:
      is_shared: True
      is_log: True
      special: eta
    T_ex:
      is_shared: False
      is_log: False
    N_tot:
      is_shared: False
      is_log: True
    delta_v:
      is_shared: True
      is_log: True
    v_LSR:
      is_shared: True
      is_log: False
peak_manager:
  noise_factor: 4.
  rel_height: 0.25
  freqs_exclude: null
n_process: 8
opt_single:
  method: "pso"
  n_swarm: 32
  n_trial: 1
opt_combine:
  method: "pso"
  n_swarm: 32
  n_trial: 1
bound_info:
  theta: [-3, -0.00043]
  T_ex:  [1.0, 1000.0]
  N_tot: [12.0, 22.0]
  delta_v: [-0.5, 1.5]
  v_LSR: [-12., 12.]
identify:
  use_f_dice: True
  criteria:
    score: 2.7
    t3_score: 0.8
inference:
  ckpt: null
  device: "cpu"
  batch_size: 128
  max_diff: 10
  num_workers: 2
cube:
  need_spectra: True