# Each item of obs_info should have the following format:
#  - spec: PATH
#    beam_info: 30. # [1/3600, 1/3600] [deg]
#    T_bg: 0.
#    need_cmb: True
#    noise: 1.
obs_info: null
fname_base: null
sl_model:
  fname_db: ""
param_info:
  theta:
    is_shared: True
    is_log: True
    special: eta
    bound: [-3, -0.00043]
  T_ex:
    is_shared: False
    is_log: False
    bound: [1.0, 1000.0]
  N_tot:
    is_shared: False
    is_log: True
    bound: [12.0, 22.0]
  delta_v:
    is_shared: True
    is_log: True
    bound: [-0.5, 1.5]
  v_offset:
    is_shared: True
    is_log: False
    bound: [-12., 12.]
peak_manager:
  noise_factor: 4.
  rel_height: 0.25
  freqs_exclude: null
n_process: 8
optimizer:
  method: "pso"
  n_swarm: 32
  n_trial: 1
identify:
  use_f_dice: True
  criteria:
    score: 2.7
    t3_score: 0.8
inference:
  ckpt: null
  device: "cpu"
  batch_size: 128
  max_diff: 10
  num_workers: 2
cube:
  need_spectra: True
