obs_info:
    - fname: None
      beam_info: 30 # (1/3600, 1/3600)
      T_bg: 0.
      need_cmb: True

    # Use the following for multiple observed segments
    #- fname: None
    #  beam_info: 30 # (1/3600, 1/3600)
    #  T_bg: 0.
    #  need_cmb: True
fname_base: null
sl_model:
  fname_db: null
  trunc: 10.
  eps_grid: 1.e-3
  params:
    theta:
      is_shared: True
      is_log: True
    T_ex:
      is_shared: False
      is_log: False
    N_tot:
      is_shared: False
      is_log: True
    delta_v:
      is_shared: True
      is_log: True
    v_LSR:
      is_shared: True
      is_log: False
peak_manager:
  prominence: null
  rel_height: 0.25
  freqs_exclude: null
opt:
  optimizer: "pso"
  bounds:
    theta: [0.7, 2.3]
    T_ex: [10., 400.]
    N_tot: [12., 20.]
    delta_v: [0., 1.5]
    v_LSR: [-10., 10.]
  n_process: 32
  n_trail: 1
  n_cycle_min: 100
  n_cycle_max: 1000
  n_cycle_dim: 5
  n_stop: 15
  tol_stop: 1.e-5
  kwargs_opt:
    nswarm: 32
  save_history: True
  save_all: True
  criteria:
    score: 2.7
    t3_score: 0.8
  blob: False