from . import ai
from .sl_model import *
from .identify import *
from .modify import *
from .optimize import *
from .slm_factory import *
from .preprocess import *
from .config import *
from .spectral_plot import *
from .cube import *
from .utils import *
from .peaks import assign_values_to_intervals
from .version import __version__