files: null
fname_base: null
sl_model:
  prefix_molfit: TMP_DIR
  Inter_Flag: False
  TelescopeSize: 30
  BMIN: null
  BMAJ: null
  BPA: null
  N_H: 0.
  kappa_1300: 0.
  beta_dust: 0.
  vLSR: 0.
  tBack: 0.
  MinNumTransitionsSQL: 1
  MaxNumTransitionsSQL: 0
  # order of transitions:
  # - 1: by lower energy
  # - 2: by gA
  # - 3: gA/E_low^2
  # - else: by trans. freq.
  TransOrderSQL: 1
  # Maximum lower energy.
  MaxElowSQL: 5000.
  # Minimum intensity.
  MingASQL: null
params:
  theta:
    is_shared: True
    is_log: True
  T_ex:
    is_shared: False
    is_log: False
  N_tot:
    is_shared: False
    is_log: True
  delta_v:
    is_shared: True
    is_log: True
  v_LSR:
    is_shared: True
    is_log: False
peak_manager:
  prominence: null
  rel_height: 0.25
  freqs_exclude: null
opt:
  optimizer: "pso"
  bounds:
    theta: [0.7, 2.3]
    T_ex: [10., 400.]
    N_tot: [12., 20.]
    delta_v: [0., 1.5]
    v_LSR: [-10., 10.]
  n_process: 32
  n_trail: 1
  n_cycle_min: 100
  n_cycle_max: 1000
  n_cycle_dim: 5
  n_stop: 15
  tol_stop: 1.e-5
  kwargs_opt:
    nswarm: 32
  save_history: True
  save_all: True
  criteria:
    score: 2.7
    t3_score: 0.8
  blob: False