files: []
fname_base: null
sl_model:
  prefix_molfit: TMP_DIR
  Inter_Flag: False
  TelescopeSize: 30
  BMIN: null
  BMAJ: null
  BPA: null
  N_H: 0.
  kappa_1300: 0.
  beta_dust: 0.
  vLSR: 0.
  tBack: 0.
  MinNumTransitionsSQL: 1
  MaxNumTransitionsSQL: 0
  # order of transitions:
  # - 1: by lower energy
  # - 2: by gA
  # - 3: gA/E_low^2
  # - else: by trans. freq.
  TransOrderSQL: 1
  # Maximum lower energy.
  MaxElowSQL: 10000.
  # Minimum intensity.
  MingASQL: null
peak_manager:
  prominence: null
  rel_height: 0.25