molecules:
  - CS
  - CCS
  - CCCS
  - H2CO
  - H2S
  - H2CS
  - H2CCO
  - HCO+
  - OCS
  - HCN
  - HCCN
  - HCCCN
  - HCCCCCN
  - HNC
  - HNCO
  - SiS
  - SiO
  - SO
  - SO2
  - CCH
  - CCCH
  - c-C3H2
  - CH3OH
  - CH3OCHO
  - CH3CHO
  - CH3OCH3
  - c-C2H4O
  - CH3SH
  - CH3CN
  - C2H3CN
  - C2H5CN
  - C2H5OH
  - C2H5CHO
  - CH3COCH3
  - CH3NH2
  - HC(O)NH2
  - NH3
  - NH2CN
iso_mode: "combined"
exclude_list: null
rename_dict: null
ElowMin: 0.0
ElowMax: 10000.
base_only: False