molecules:
  - CO
  - CS
  - CCS
  - CCCS
  - H2CO
  - H2CCO
  - H2S
  - H2CS
  - HCOOH
  - HCO+
  - HCS+
  - HOC+
  - OCS
  - HCN
  - HCCN
  - HCCCN
  - HCCCCCN
  - HNC
  - HNCO
  - CCH
  - c-C3H2
  - c-C2H4O
  - CH3OH
  - CH3CHO
  - CH3CCH
  - CH3OCHO
  - CH3OCH3
  - CH3CN
  - C2H3CN
  - C2H5CN
  - C2H5OH
  - CH3COCH3
  - CH3NH2
  - HC(O)NH2
  - NH3
  - SO
  - SO2
  - SiO
  - SiS
iso_mode: "combined"
sort_mode: "default"
include_hyper: False
exclude_list: null
rename_dict: null
ElowMin: 0.0
ElowMax: 5000.
base_only: False