elements: ["H", "D", "C", "N", "O", "S", "Si", "Na", "Cl", "P"]
molecules:
  - CS
  - CCS
  - CCCS
  - H2CO
  - H2S
  - H2CS
  - OCS
  - HCN
  - HNC
  - SiS
  - SiO
  - NH3
  - c-C3H2
  - SO
  - SO2
  - H2CCO
  - HNCO
  - CH3OH
  - CH3OCHO
  - CH3CHO
  - CH3OCH3
  - CH2OCH2
  - CH3SH
  - CH3CN
  - C2H3CN
  - C2H5CN
  - C2H5OH
  - C2H5CHO
  - CH3COCH3
  - HC(O)NH2
  - HCCCN
  - HCCCCCN
  - CH3NH2
  - NH2CN
iso_list: []
exclude_list: [
  "HNC3;v=0;", # Duplicated
  "H2C-13-CHCN;v=0;", # Duplicated
  "H2CC-13-HCN;v=0;", # Duplicated
  "H2CCHC-13-N;v=0;", # Duplicated
]
rename_dict:
  "NH2CN": "H2NCN"
  "H2CCHCN-15": "CH2CHCN-15"
  "C2H3CN": "CH2CHCN"
  "C-13-H3C-13-H2C-13-N": "C2H5CN"
ElowMin: 0.0
ElowMax: 5000.
base_only: False